// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mgmotorctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CMgmotorctrl1

IMPLEMENT_DYNCREATE(CMgmotorctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMgmotorctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CMgmotorctrl1 operations
