//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by openOCT.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SDOCT_DIALOG                102
#define IDD_OCT_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDR_INTENSITYTOOLBAR            136
#define IDR_PHASETOOLBAR                137
#define IDR_CURVETOOLBAR                138
#define IDD_CURVE_DLG                   138
#define IDR_MOVIETOOLBAR                139
#define IDD_INTENSITY_DLG               139
#define IDD_PHASE_DLG                   140
#define IDR_CURVE_TOOLBAR1              141
#define IDR_TOOLBAR                     141
#define IDB_OCTLAB                      145
#define IDB_ABOUT                       146
#define IDB_BITMAP1                     147
#define IDB_BITMAP3                     150
#define IDB_FLOW                        150
#define IDB_BITMAP4                     151
#define IDB_CELL                        151
#define IDB_BITMAP2                     153
#define IDC_CHECK3                      1000
#define IDC_CHECK_AOI_RESIZE            1000
#define IDC_HOT_COLOR                   1000
#define IDC_IMAQ                        1001
#define IDC_RECONSTRUCT_IMAGE           1001
#define IDC_CAM                         1002
#define IDC_SCAN                        1003
#define IDC_CAM2                        1003
#define IDC_CHECK1                      1004
#define IDC_AXIAL_LINE                  1004
#define IDC_AXIAL_Intensity             1004
#define IDC_AXIAL_INTENSITY             1004
#define IDC_AOI                         1004
#define IDC_COMBO1                      1005
#define IDC_CALIED_SPECTRUM             1005
#define IDC_ZOOM                        1005
#define IDC_SCAN_BACKWARD               1005
#define IDC_RAW_SPECTRUM                1006
#define IDC_EXPAND                      1006
#define IDC_SCAN_STEPX                  1006
#define IDC_DATETIMEPICKER1             1007
#define IDC_AXIAL_LINE2                 1007
#define IDC_AXIAL_PHASE                 1007
#define IDC_EXPAND2                     1007
#define IDC_LOG                         1007
#define IDC_SCAN_STEPY                  1007
#define IDC_RAW_SPECTRUM2               1008
#define IDC_POWER                       1008
#define IDC_BUTTON5                     1013
#define IDC_REPLAY                      1013
#define IDC_FILE_PATH                   1014
#define IDC_START_CURVE                 1015
#define IDC_SAVE_CURVE                  1016
#define IDC_PAUSE_CURVE                 1017
#define IDC_PAUSE_INTENSITY             1017
#define IDC_SAVE_CURVE2                 1018
#define IDC_LOAD_CURVE                  1018
#define IDC_LOAD_INTENSITY              1018
#define IDC_STOP_CURVE                  1019
#define IDC_SAVE_INTENSITY              1019
#define IDC_MOTOR_STEP                  1019
#define IDC_MOTOR_STEPSIZE              1019
#define IDC_CUSTOM1                     1020
#define IDC_RECON_IMAGES                1020
#define IDC_LOAD_INTENSITY2             1020
#define IDC_RECON_INTENSITY             1020
#define IDC_MOTOR_STEPSIZE2             1020
#define IDC_FRAME_SHIFT                 1020
#define IDC_SAVE_INTENSITY2             1021
#define IDC_SNAP                        1021
#define IDC_START_INTENSITY             1022
#define IDC_ENABLE_STAGE                1023
#define IDC_START_PHASE                 1025
#define IDC_PAUSE_PHASE                 1026
#define IDC_SAVE_PHASE                  1027
#define IDC_INTENSITY_TEXT              1031
#define IDC_INTENSITY_TEXT1             1031
#define IDC_INTENSITY_SLIDER            1032
#define IDC_INTENSITY_GAIN              1032
#define IDC_CONTRAST_TEXT               1033
#define IDC_INTENSITY_TEXT2             1033
#define IDC_CAM_IT_SLIDER               1033
#define IDC_INTENSITY_OFFSET            1033
#define IDC_INTENSITY_SLIDER2           1034
#define IDC_CONTRAST_SLIDER             1034
#define IDC_SCAN_VMAX                   1034
#define IDC_SCAN_VMAXX                  1034
#define IDC_SCAN_VMIN                   1035
#define IDC_SCAN_VMINX                  1035
#define IDC_SCAN_STEP_NUM               1036
#define IDC_A_LINE_NUM                  1036
#define IDC_CAM_GAIN                    1037
#define IDC_CAM_IT                      1038
#define IDC_IMAQ_SETTING_OK             1039
#define IDC_IMAQ_FRAMES_START           1039
#define IDC_SCAN_SETTING_OK             1040
#define IDC_ODDPIX_GAIN_CALI            1040
#define IDC_IMAQ_FRAMES_STOP            1040
#define IDC_CAM_SETTING_OK              1041
#define IDC_SCAN_RESET                  1041
#define IDC_RESET_IMAQ                  1041
#define IDC_SCAN_VMINY                  1042
#define IDC_FRAME_NUM                   1043
#define IDC_FRAME_NUM2                  1044
#define IDC_FRAME_RATE                  1044
#define IDC_ITERATION_NUM               1044
#define IDC_SCAN_FREQ                   1045
#define IDC_AVG_NUM                     1046
#define IDC_DELAY_TIME                  1047
#define IDC_FRAME_INTERVAL              1047
#define IDC_DISPERSION                  1047
#define IDC_SCAN_VMAXY                  1048
#define IDC_CAM_GAIN_SLIDER             1049
#define IDC_VOLTAGE                     1051
#define IDC_VOLTAGEY                    1051
#define IDC_INTENSITY                   1052
#define IDC_LOAD_PHASE                  1052
#define IDC_PHASE                       1053
#define IDC_VOLTAGEX                    1053
#define IDC_DEPTH                       1054
#define IDC_MGMOTORCTRL1                1058
#define IDC_AUTOSAVE                    1059
#define IDC_FILE_SPIN                   1061
#define IDC_PATH                        1064
#define IDC_BUTTON1                     1065
#define IDC_FILEPATH_BUTTON             1065
#define IDC_FILENAME                    1068
#define IDC_FILE_INDEX                  1068
#define IDC_PHASE_THRESH                1072
#define IDC_SLIDER3                     1074
#define ID_BUTTON32772                  32772
#define ID_LOAD_CONF                    32772
#define ID_MOVIE                        32775
#define ID_BUTTON32776                  32776
#define ID_PHASE                        32777
#define ID_CURVE                        32778
#define ID_BUTTON32779                  32779
#define ID_INTENSITY                    32780
#define ID_BUTTON32781                  32781
#define ID_SAVE_CURVE                   32782
#define ID_SAVE_INTENSITY_IMG           32783
#define ID_SAVE_MOVIE_AVI               32784
#define ID_SAVE_PHASE_IMG               32785
#define ID_SAVE_RAWDATA                 32787
#define ID_SAVE_CONF                    32787
#define ID_BUTTON32788                  32788
#define ID_RESET_WND_POS                32789
#define ID_STARTSDOCT                   32792
#define ID_START_IMAQ                   32792
#define IDC_START_IMAQ                  32792
#define ID_CALIBRATION_IMAQ             32793
#define IDC_CALIBRATION_IMAQ            32793
#define ID_PAUSE_IMAQ                   32795
#define IDC_PAUSE_IMAQ                  32795
#define ID_GETREF_IMAQ                  32797
#define IDC_GETREF_IMAQ                 32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
